<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Makman_Data-windows\Makman_Data-windows.csproj" />
    <ProjectReference Include="..\Makman_Entities\Makman_Entities.csproj" />
    <ProjectReference Include="..\Makman_Localization\Makman_Localization.csproj" />
  </ItemGroup>

</Project>
