//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makman.Visual.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Makman.Visual.Localization.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto.
        /// </summary>
        public static string dir_itemspanel_headers_autoscanning {
            get {
                return ResourceManager.GetString("dir itemspanel headers autoscanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autoscanning.
        /// </summary>
        public static string dir_itemspanel_headers_autoscanning_tt {
            get {
                return ResourceManager.GetString("dir itemspanel headers autoscanning tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string dir_itemspanel_headers_id {
            get {
                return ResourceManager.GetString("dir itemspanel headers id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path.
        /// </summary>
        public static string dir_itemspanel_headers_path {
            get {
                return ResourceManager.GetString("dir itemspanel headers path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync.
        /// </summary>
        public static string dir_itemspanel_headers_sync {
            get {
                return ResourceManager.GetString("dir itemspanel headers sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync with cloud.
        /// </summary>
        public static string dir_itemspanel_headers_sync_tt {
            get {
                return ResourceManager.GetString("dir itemspanel headers sync tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag.
        /// </summary>
        public static string dir_itemspanel_headers_tag {
            get {
                return ResourceManager.GetString("dir itemspanel headers tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Special tag.
        /// </summary>
        public static string dir_itemspanel_headers_tag_tt {
            get {
                return ResourceManager.GetString("dir itemspanel headers tag tt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☉.
        /// </summary>
        public static string dir_itemspanel_id {
            get {
                return ResourceManager.GetString("dir itemspanel id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change path.
        /// </summary>
        public static string dir_managepanel_changepath {
            get {
                return ResourceManager.GetString("dir managepanel changepath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        public static string dir_managepanel_connect {
            get {
                return ResourceManager.GetString("dir managepanel connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        public static string dir_managepanel_disconnect {
            get {
                return ResourceManager.GetString("dir managepanel disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Makman.
        /// </summary>
        public static string mw_makman {
            get {
                return ResourceManager.GetString("mw makman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection.
        /// </summary>
        public static string mw_pagelist_collection {
            get {
                return ResourceManager.GetString("mw pagelist collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Directories.
        /// </summary>
        public static string mw_pagelist_directories_manager {
            get {
                return ResourceManager.GetString("mw pagelist directories manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string mw_pagelist_home {
            get {
                return ResourceManager.GetString("mw pagelist home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag Categories.
        /// </summary>
        public static string mw_pagelist_tag_categories_manager {
            get {
                return ResourceManager.GetString("mw pagelist tag categories manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        public static string mw_pagelist_tags_manager {
            get {
                return ResourceManager.GetString("mw pagelist tags manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string tag_category_itemspanel_headers_color {
            get {
                return ResourceManager.GetString("tag category itemspanel headers color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string tag_category_itemspanel_headers_id {
            get {
                return ResourceManager.GetString("tag category itemspanel headers id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string tag_category_itemspanel_headers_name {
            get {
                return ResourceManager.GetString("tag category itemspanel headers name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☉.
        /// </summary>
        public static string tag_category_itemspanel_id {
            get {
                return ResourceManager.GetString("tag category itemspanel id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new tag category.
        /// </summary>
        public static string tag_category_managepanel_add {
            get {
                return ResourceManager.GetString("tag category managepanel add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string tag_category_managepanel_remove {
            get {
                return ResourceManager.GetString("tag category managepanel remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string tag_itemspanel_headers_category {
            get {
                return ResourceManager.GetString("tag itemspanel headers category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string tag_itemspanel_headers_color {
            get {
                return ResourceManager.GetString("tag itemspanel headers color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id.
        /// </summary>
        public static string tag_itemspanel_headers_id {
            get {
                return ResourceManager.GetString("tag itemspanel headers id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string tag_itemspanel_headers_name {
            get {
                return ResourceManager.GetString("tag itemspanel headers name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parent tag.
        /// </summary>
        public static string tag_itemspanel_headers_parenttag {
            get {
                return ResourceManager.GetString("tag itemspanel headers parenttag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ☉.
        /// </summary>
        public static string tag_itemspanel_id {
            get {
                return ResourceManager.GetString("tag itemspanel id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new tag.
        /// </summary>
        public static string tag_managepanel_add {
            get {
                return ResourceManager.GetString("tag managepanel add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pick category.
        /// </summary>
        public static string tag_managepanel_pickcategory {
            get {
                return ResourceManager.GetString("tag managepanel pickcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string tag_managepanel_remove {
            get {
                return ResourceManager.GetString("tag managepanel remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text now missing.
        /// </summary>
        public static string u_no_text {
            get {
                return ResourceManager.GetString("u no text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string u_search {
            get {
                return ResourceManager.GetString("u search", resourceCulture);
            }
        }
    }
}
